[botdetection]
# how precise to compare addresses
ipv4_prefix = 32
ipv6_prefix = 48

# trusted proxies list (so X-Forwarded-For can be used safely)
trusted_proxies = [
  "127.0.0.0/8",
  "::1"
]

[botdetection.ip_limit]
# do not block link-local networks for local dev
filter_link_local = false
# keep link_token off for local dev
link_token = false

[botdetection.ip_lists]
# simple empty lists
block_ip = []
pass_ip = []
# accept SearXNG org passlist (harmless for local dev)
pass_searxng_org = true
